defaults: &defaults
  adapter: postgis
  encoding: unicode
  username: robert_thesis_pg_user
  password: login_password
  pool: 5
  host: localhost
  port: 5432

  # PostGIS 2:
  postgis_extension: postgis

development:
  <<: *defaults
  database: robertpyke_thesis_dev_database

test:
  <<: *defaults
  database: robertpyke_thesis_test_database

production:
  <<: *defaults
  database: robertpyke_thesis_prod_database
