defaults: &defaults
  adapter: postgis
  encoding: unicode
  username: robert_thesis_pg_user
  password: login_password
  pool: 5
  host: localhost
  port: 5432
  script_dir: /usr/share/postgresql/9.1/contrib/postgis-1.5/

development:
  <<: *defaults
  database: robertpyke_thesis_dev_database

test:
  <<: *defaults
  database: robertpyke_thesis_test_database

production:
  <<: *defaults
  database: robertpyke_thesis_prod_database
