development:
  adapter: postgis
  encoding: unicode
  database: robertpyke_thesis_dev_database
#  username:
#  password:
  pool: 5
  host: localhost
  port: 5432

test:
  adapter: postgis
  encoding: unicode
  database: robertpyke_thesis_test_database
#  username:
#  password:
  pool: 5
  host: localhost
  port: 5432

production:
  adapter: postgis
  encoding: unicode
  database: robertpyke_thesis_prod_database
#  username:
#  password:
  pool: 5
  host: localhost
  port: 5432
