#!/bin/sh

# A hook to ensure that all tests are currently passing
#
# You can add this hook by running the following from the root of this repo:
#
#   ln -s ../../hooks/pre-commit .git/hooks/pre-commit
#
# If you want to allow tests to fail, set this variable to true by running:
#
#     git config hooks.allowteststofail true
#
allowteststofail=$(git config hooks.allowteststofail)

if [ "$allowteststofail" = "true" ]; then
  echo
  echo "You're bypassing the pre-commit hook that checks that all tests are passing."
  echo
  exit 0
else
  cd "webapp"

  echo
  rake
  test_exit_code=$?
  echo

  cd ../
  if [ "$test_exit_code" != "0" ]; then

    # Redirect output to stderr.
    exec 1>&2
    echo
    echo "You failed some tests. Fix your code, then try again."
    echo
    echo "You can bypass this pre-commit hook by running:"
    echo
    echo "  git config hooks.allowteststofail true"
    echo
    exit 1
  fi
fi
